# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Corentin Nelias
tagline:          'A Jekyll theme'
description:      'My website'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Corentin Nelias'

paginate:         5

plugins:
  - jekyll-paginate

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
